In [5]:
import numpy as np
from sklearn.model_selection import train_test_split

In [8]:
X,y=np.arange(10).reshape((5,2)),range(5)
print(X)
print([i for i in y])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0, 1, 2, 3, 4]


输入：要划分的数据（X,y）
    校验集的大小（test_size）
    随机种子（random_state）
    
test表示校验集

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)
print(X_train,'\n',y_train)
print('\n',X_test,'\n',y_test)

[[4 5]
 [0 1]
 [6 7]] 
 [2, 0, 3]

 [[2 3]
 [8 9]] 
 [1, 4]
