In [16]:
import numpy as np
from sklearn.model_selection import StratifiedKFold

In [17]:
X=np.array([[1,2],[2,4],[1,3],[3,4]])
y=np.array([0,0,1,1])
skf=StratifiedKFold(n_splits=2)
skf.get_n_splits(X,y)

2

In [21]:
for train_index,test_index in skf.split(X,y):
    print("\n train:\n",X[train_index],'\n',y[train_index])
    print("test:\n",X[test_index],'\n',y[test_index],'\n')


 train:
 [[2 4]
 [3 4]] 
 [0 1]
test:
 [[1 2]
 [1 3]] 
 [0 1] 


 train:
 [[1 2]
 [1 3]] 
 [0 1]
test:
 [[2 4]
 [3 4]] 
 [0 1] 

